Global:

  label_names: ["lumo"]

  graph_converter:
    __class_name__: FindPointsInSpheres
    __init_params__:
        cutoff: 5.0
        num_cpus: 10

Dataset:
  train:
    dataset:
      __class_name__: OMol25Dataset
      __init_params__:
        path: "./data/omol25"
        property_names: ${Global.label_names}
        build_graph_cfg: ${Global.graph_converter}
        cache_path: "./data/omol25"
    num_workers: 4
    use_shared_memory: False
    sampler:
      __class_name__: BatchSampler
      __init_params__:
        shuffle: True
        drop_last: False
        batch_size: 128

  val:
    dataset:
      __class_name__: OMol25Dataset
      __init_params__:
        path: "./data/omol25"
        property_names: ${Global.label_names}
        build_graph_cfg: ${Global.graph_converter}
        cache_path: "./data/omol25"
    num_workers: 4
    use_shared_memory: False
    sampler:
      __class_name__: BatchSampler
      __init_params__:
        shuffle: False
        drop_last: False
        batch_size: 128

Model:
  __class_name__: MEGNetPlus
  __init_params__:
    dim_node_embedding: 16
    dim_edge_embedding: 100
    dim_state_embedding: 2
    nblocks: 3
    nlayers_set2set: 1
    niters_set2set: 2
    bond_expansion_cfg:
      rbf_type: "Gaussian"
      initial: 0.0
      final: 5.0
      num_centers: 100
      width: 0.5
    property_name: ${Global.label_names}

Trainer:
  max_epochs: 2000
  seed: 42
  output_dir: ./output/megnet_omol25_dipole
  save_freq: 100
  log_freq: 20
  start_eval_epoch: 1
  eval_freq: 1
  pretrained_model_path: null
  pretrained_weight_name: null
  resume_from_checkpoint: null
  use_amp: False
  amp_level: 'O1'
  eval_with_no_grad: True
  gradient_accumulation_steps: 1
  best_metric_indicator: 'eval_metric'
  name_for_best_metric: "dipole"
  greater_is_better: False
  compute_metric_during_train: True
  metric_strategy_during_eval: 'epoch'
  use_visualdl: False
  use_wandb: False
  use_tensorboard: False

Optimizer:
  __class_name__: Adam
  __init_params__:
    beta1: 0.9
    beta2: 0.999
    lr:
      __class_name__: Cosine
      __init_params__:
        learning_rate: 0.001
        eta_min: 0.0001
        by_epoch: True

Metric:
  dipole:
    __class_name__: paddle.nn.L1Loss
    __init_params__: {}

Predict:
  graph_converter: ${Global.graph_converter}
  eval_with_no_grad: True
